name: lsandroid
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  win32: ^5.5.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.19.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.2
  dio: ^5.7.0
  url_launcher: ^6.1.3
  http: ^1.0.0
  table_calendar: ^3.0.9
  flutter_holo_date_picker: ^1.1.2+1
  file_picker: ^5.2.0+1
  printing: ^5.11.0
  fluttertoast: ^8.2.8
  permission_handler: ^10.4.3
  pdf: ^3.10.4
  image: ^4.1.3
  loading_animation_widget: ^1.2.0+4
  pluto_grid: ^8.0.0
  flutter_local_notifications: ^17.2.3
  ##### ------------------------- flutter_foreground_task + 종속
  plugin_platform_interface: ^2.1.5
  platform: ^3.1.1
  ##shared_preferences: ^2.2.0
  flutter_foreground_task: ^8.10.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  excel: ^4.0.6
  path_provider: ^2.1.4
  freedom_table: ^0.3.6+3
  vs_scrollbar: ^1.0.0
  flutter_layout_grid: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/app/
    - assets/json/
    - assets/json/login/
    - assets/font/godic.ttf


flutter_icons:
  ios: true
  android: true
  image_path: "assets/app/29-2.png"
  remove_alpha_ios: true